### ISSUE TITLE
Colormap Plot has blank areas where dNdlogDp is less than Z.min()

### ISSUE THREAD

**Issue by dhhagan** [dhhagan/py-smps#2]
Should we somehow fix this heatmap so that any datapoint less than the LogNorm minimum appears visually as the minimum? i.e. If we set `cbar_min=100`, then any data point where dNdlogDp < 100 will appear white, rather than the minimum colorbar color..

**Comment by asongtoruin** [comment]
Could this be achieved by applying a filter to the `Z` data immediately before calling `ax.pcolormesh`? In some cases the flagging of non-matching data might be useful, so this could be made an optional feature, using another input parameter for `smps.plots.heatmap`, i.e. `mask_low`?

**Comment by dhhagan** [comment]
@asongtoruin Sounds like it could certainly work. The times I've noticed the issue is when there are NaNs or 0's in the matrix, because it is plotted on a log scale. Ideally, the 0 or NaN values would be set to appear as the minimum value (color) on the map. Does that make sense?

**Comment by asongtoruin** [comment]
Okay, so I gave this a quick go with the `'Cambridge MA Wintertime'` data from the examples. My initial thought was to just set any values below the minimum to be the minimum value before plotting. This changes your output heatmap quite significantly, I think due to the interpolation used by `pcolormesh`.

**Before:**
![original](https://user-images.githubusercontent.com/20771863/31045046-6932fd2c-a5d3-11e7-9990-1aa2412c6149.png)

**After**
![hidden_low](https://user-images.githubusercontent.com/20771863/31045047-69356a12-a5d3-11e7-9f81-9ca1de50082a.png)

Thoughts?

**Comment by dhhagan** [comment]
@asongtoruin Interesting. In general, I don't think it matters too much since it is just a visual relative representation. What if there was a keyword arg for the minimum value that the user could set, with the default being the minimum value in the Z matrix? It also may be interesting to test with a file that has NaNs in the matrix (or artificially set some?). I will try to upload one later today.

**Comment by asongtoruin** [comment]
At the moment I've set it to use the `cbar_min` that you pop from the `cbar_args` , so that it's consistent with the colour bar.

**Comment by dhhagan** [comment]
Ahh that's perfect. Whenever you're confident, go ahead and send a PR then and I'll try it out/merge.
